import type { WorldConfig } from "../types";

export const WORLDS: WorldConfig[] = [
  {
    id: "world_1",
    name: "Isla de las Palabras",
    phase: 1,
    description: "Descubre tus primeras palabras en esta isla mágica",
    color: "#48bb78",
    icon: "🏝️",
    image: "/images/worlds/isla.png",
    categories: ["familia", "colores", "animales", "comida", "casa", "cuerpo"],
    availableGames: ["leo-runner", "salta-palabra", "leo-vuela", "word-flash", "word-image-match", "memory-cards"],
    totalWords: 50,
  },
  {
    id: "world_2",
    name: "Bahía de los Pares",
    phase: 2,
    description: "Combina palabras para crear ideas nuevas",
    color: "#667eea",
    icon: "🌊",
    image: "/images/worlds/bahia.png",
    categories: ["colores", "tamaños_y_formas", "opuestos", "emociones", "naturaleza"],
    availableGames: ["leo-runner", "salta-palabra", "word-train", "category-sort"],
    totalWords: 50,
  },
  {
    id: "world_3",
    name: "Valle de las Frases",
    phase: 3,
    description: "Construye tus primeras oraciones",
    color: "#fbbf24",
    icon: "🌄",
    image: "/images/worlds/valle.png",
    categories: ["verbos_cotidianos", "verbos_de_accion", "ropa", "escuela", "lugares"],
    availableGames: ["leo-runner", "salta-palabra", "phrase-builder", "word-rain"],
    totalWords: 50,
  },
  {
    id: "world_4",
    name: "Montaña de la Lectura",
    phase: 4,
    description: "Domina frases completas y lee como un campeón",
    color: "#f56565",
    icon: "🏔️",
    image: "/images/worlds/montana.png",
    categories: ["articulos_y_conectores", "preposiciones", "pronombres", "tiempo", "numeros"],
    availableGames: ["leo-runner", "salta-palabra", "word-fishing"],
    totalWords: 50,
  },
  {
    id: "world_5",
    name: "El Libro Mágico",
    phase: 5,
    description: "Lee cuentos y crea tu propio libro",
    color: "#f093fb",
    icon: "📖",
    image: "/images/worlds/libro.png",
    categories: ["verbos_avanzados", "adverbios"],
    availableGames: ["daily-bits"],
    totalWords: 20,
  },
];
