import { Affirmation } from "../types/doman";

export const AFFIRMATIONS: Affirmation[] = [
  // ─── Autoconocimiento y Valor Personal ───────────────────────────────
  {
    id: "auto-01",
    text: "Yo soy importante",
    category: "autoconocimiento",
    moment: "session_start",
    audioUrl: "AUTO",
  },
  {
    id: "auto-02",
    text: "Yo amo quien soy",
    category: "autoconocimiento",
    moment: "session_end",
    audioUrl: "AUTO",
  },
  {
    id: "auto-03",
    text: "Soy valioso",
    category: "autoconocimiento",
    moment: "achievement",
    audioUrl: "AUTO",
  },
  {
    id: "auto-04",
    text: "Me quiero tal y como soy",
    category: "autoconocimiento",
    moment: "session_start",
    audioUrl: "AUTO",
  },
  {
    id: "auto-05",
    text: "Yo soy único y especial",
    category: "autoconocimiento",
    moment: "achievement",
    audioUrl: "AUTO",
  },
  {
    id: "auto-06",
    text: "No hay nadie como yo en el mundo",
    category: "autoconocimiento",
    moment: "session_end",
    audioUrl: "AUTO",
  },
  {
    id: "auto-07",
    text: "Estoy orgulloso de ser yo",
    category: "autoconocimiento",
    moment: "achievement",
    audioUrl: "AUTO",
  },
  {
    id: "auto-08",
    text: "Merezco amor y respeto",
    category: "autoconocimiento",
    moment: "session_start",
    audioUrl: "AUTO",
  },
  {
    id: "auto-09",
    text: "Soy suficiente tal como soy",
    category: "autoconocimiento",
    moment: "session_end",
    audioUrl: "AUTO",
  },

  // ─── Confianza y Capacidad ─────────────────────────────────────────
  {
    id: "conf-01",
    text: "Yo creo en mí",
    category: "confianza",
    moment: "session_start",
    audioUrl: "AUTO",
  },
  {
    id: "conf-02",
    text: "Yo soy inteligente",
    category: "confianza",
    moment: "correct_answer",
    audioUrl: "AUTO",
  },
  {
    id: "conf-03",
    text: "Soy capaz de aprender cosas nuevas",
    category: "confianza",
    moment: "correct_answer",
    audioUrl: "AUTO",
  },
  {
    id: "conf-04",
    text: "Puedo hacerlo si lo intento",
    category: "confianza",
    moment: "after_attempt",
    audioUrl: "AUTO",
  },
  {
    id: "conf-05",
    text: "Cada día aprendo algo nuevo",
    category: "confianza",
    moment: "session_end",
    audioUrl: "AUTO",
  },
  {
    id: "conf-06",
    text: "Soy valiente",
    category: "confianza",
    moment: "session_start",
    audioUrl: "AUTO",
  },
  {
    id: "conf-07",
    text: "Confío en mis habilidades",
    category: "confianza",
    moment: "correct_answer",
    audioUrl: "AUTO",
  },
  {
    id: "conf-08",
    text: "Lo intento y lo logro",
    category: "confianza",
    moment: "after_attempt",
    audioUrl: "AUTO",
  },
  {
    id: "conf-09",
    text: "Soy bueno resolviendo problemas",
    category: "confianza",
    moment: "achievement",
    audioUrl: "AUTO",
  },

  // ─── Relaciones y Apoyo ────────────────────────────────────────────
  {
    id: "rel-01",
    text: "Hay muchas personas que se preocupan por mí",
    category: "relaciones",
    moment: "session_start",
    audioUrl: "AUTO",
  },
  {
    id: "rel-02",
    text: "Soy querido por mi familia",
    category: "relaciones",
    moment: "session_end",
    audioUrl: "AUTO",
  },
  {
    id: "rel-03",
    text: "Mis amigos me aprecian",
    category: "relaciones",
    moment: "session_start",
    audioUrl: "AUTO",
  },
  {
    id: "rel-04",
    text: "Siempre puedo pedir ayuda",
    category: "relaciones",
    moment: "after_attempt",
    audioUrl: "AUTO",
  },
  {
    id: "rel-05",
    text: "Soy un buen amigo",
    category: "relaciones",
    moment: "session_end",
    audioUrl: "AUTO",
  },
  {
    id: "rel-06",
    text: "Trato a los demás con respeto",
    category: "relaciones",
    moment: "session_end",
    audioUrl: "AUTO",
  },
  {
    id: "rel-07",
    text: "Comparto con alegría",
    category: "relaciones",
    moment: "correct_answer",
    audioUrl: "AUTO",
  },

  // ─── Específicas para Lectura ──────────────────────────────────────
  {
    id: "lect-01",
    text: "Me encanta aprender a leer",
    category: "lectura",
    moment: "session_start",
    audioUrl: "AUTO",
  },
  {
    id: "lect-02",
    text: "Cada palabra que leo me hace más fuerte",
    category: "lectura",
    moment: "correct_answer",
    audioUrl: "AUTO",
  },
  {
    id: "lect-03",
    text: "Leer me abre puertas a nuevos mundos",
    category: "lectura",
    moment: "achievement",
    audioUrl: "AUTO",
  },
  {
    id: "lect-04",
    text: "Disfruto practicar todos los días",
    category: "lectura",
    moment: "session_start",
    audioUrl: "AUTO",
  },
  {
    id: "lect-05",
    text: "Cada intento me acerca más a mi meta",
    category: "lectura",
    moment: "after_attempt",
    audioUrl: "AUTO",
  },
  {
    id: "lect-06",
    text: "Me siento orgulloso de mi progreso",
    category: "lectura",
    moment: "session_end",
    audioUrl: "AUTO",
  },
  {
    id: "lect-07",
    text: "Aprender es divertido",
    category: "lectura",
    moment: "session_start",
    audioUrl: "AUTO",
  },
  {
    id: "lect-08",
    text: "Soy un gran lector",
    category: "lectura",
    moment: "achievement",
    audioUrl: "AUTO",
  },
  {
    id: "lect-09",
    text: "Los errores me ayudan a mejorar",
    category: "lectura",
    moment: "after_attempt",
    audioUrl: "AUTO",
  },
];
