// GENERADO por scripts/regenerate-oraciones.py — no editar a mano.
// Frase de Construye la Frase → MP3 en public/audio/sofia (voz Jessica).
// sofiaVoice.ts lo suma a PHRASE_TO_MP3 para que sofiaReads() la encuentre.
export const ORACIONES_AUDIO: Record<string, string> = {
  "mamá y papá": "oracion-mama-y-papa",
  "abuela y abuelo": "oracion-abuela-y-abuelo",
  "hermano y hermana": "oracion-hermano-y-hermana",
  "perro y gato": "oracion-perro-y-gato",
  "mano y pie": "oracion-mano-y-pie",
  "ojo y nariz": "oracion-ojo-y-nariz",
  "pan con leche": "oracion-pan-con-leche",
  "agua y huevo": "oracion-agua-y-huevo",
  "mesa y silla": "oracion-mesa-y-silla",
  "casa y puerta": "oracion-casa-y-puerta",
  "manzana y banana": "oracion-manzana-y-banana",
  "uva y pera": "oracion-uva-y-pera",
  "rojo y azul": "oracion-rojo-y-azul",
  "grande y pequeño": "oracion-grande-y-pequeno",
  "arriba y abajo": "oracion-arriba-y-abajo",
  "feliz y contento": "oracion-feliz-y-contento",
  "sol y luna": "oracion-sol-y-luna",
  "rápido y lento": "oracion-rapido-y-lento",
  "caliente y frío": "oracion-caliente-y-frio",
  "cerca y lejos": "oracion-cerca-y-lejos",
  "dentro y fuera": "oracion-dentro-y-fuera",
  "árbol y flor": "oracion-arbol-y-flor",
  "estrella y nube": "oracion-estrella-y-nube",
  "río y mar": "oracion-rio-y-mar",
  "mamá come pan": "oracion-mama-come-pan",
  "papá lee libro": "oracion-papa-lee-libro",
  "el perro corre": "oracion-el-perro-corre",
  "bebé duerme": "oracion-bebe-duerme",
  "gato bebe leche": "oracion-gato-bebe-leche",
  "hermana canta": "oracion-hermana-canta",
  "abuela cocina": "oracion-abuela-cocina",
  "hermano dibuja": "oracion-hermano-dibuja",
  "mamá abre puerta": "oracion-mama-abre-puerta",
  "papá baja": "oracion-papa-baja",
  "camisa y pantalón": "oracion-camisa-y-pantalon",
  "zapato y gorra": "oracion-zapato-y-gorra",
  "libro y lápiz": "oracion-libro-y-lapiz",
  "escuela y parque": "oracion-escuela-y-parque",
  "mamá lava plato": "oracion-mama-lava-plato",
  "hermana pinta": "oracion-hermana-pinta",
  "niño salta": "oracion-nino-salta",
  "ella baila": "oracion-ella-baila",
  "él escribe": "oracion-el-escribe",
  "mamá limpia casa": "oracion-mama-limpia-casa",
  "el gato y la gata": "oracion-el-gato-y-la-gata",
  "un perro grande": "oracion-un-perro-grande",
  "yo y tú": "oracion-yo-y-tu",
  "hoy y mañana": "oracion-hoy-y-manana",
  "uno dos tres": "oracion-uno-dos-tres",
  "en la casa": "oracion-en-la-casa",
  "para mi mamá": "oracion-para-mi-mama",
  "sobre la mesa": "oracion-sobre-la-mesa",
  "entre tú y yo": "oracion-entre-tu-y-yo",
  "sin zapatos": "oracion-sin-zapatos",
  "cuatro y cinco": "oracion-cuatro-y-cinco",
  "siempre y nunca": "oracion-siempre-y-nunca",
  "quiere y puede": "oracion-quiere-y-puede",
  "muy bien": "oracion-muy-bien",
  "dice y busca": "oracion-dice-y-busca",
  "aquí y allí": "oracion-aqui-y-alli",
  "más y menos": "oracion-mas-y-menos",
  "también junto": "oracion-tambien-junto",
  "el gato juega con la pelota": "oracion-el-gato-juega-con-la-pelota",
  "la niña come una manzana roja": "oracion-la-nina-come-una-manzana-roja",
  "mi mamá cocina en la cocina": "oracion-mi-mama-cocina-en-la-cocina",
  "el perro grande corre en el parque": "oracion-el-perro-grande-corre-en-el-parque",
  "yo leo un libro con mi papá": "oracion-yo-leo-un-libro-con-mi-papa",
  "la abuela y el abuelo están en casa": "oracion-la-abuela-y-el-abuelo-estan-en-casa",
  "tres gatos duermen sobre la cama": "oracion-tres-gatos-duermen-sobre-la-cama",
  "ella dibuja una flor amarilla": "oracion-ella-dibuja-una-flor-amarilla",
};
