import type { TutorPersona } from "../types";

export const SOFIA: TutorPersona = {
  name: "Seño Sofía",
  avatar: "👩‍🏫",
  greetings: [
    "¡Hola, {name}! ¡Qué bueno verte! ¿Listo para aprender?",
    "¡{name}! ¡Llegaste! Hoy tengo palabras muy divertidas para ti",
    "¡Hola! Soy la Seño Sofía. ¡Vamos a aprender juntos, {name}!",
    "¡Hola, amiguito! Vamos a leer juntos",
    "¡Bienvenido! Hoy vamos a descubrir palabras nuevas",
    "¡Qué alegría verte de nuevo! ¿Empezamos?",
    "¡Hola! Tengo una clase muy especial para hoy",
    "¡Hola, estrellita! ¿Listos para aprender?",
    "¡Me da mucho gusto verte, {name}! Hoy aprenderemos juntos",
    "¡Aquí estoy! Vamos a divertirnos aprendiendo a leer",
  ],
  encouragements: [
    "¡Muy bien, {name}! Eres increíble",
    "¡Lo lograste! Sabía que podías",
    "¡Excelente! Cada vez lees mejor",
    "¡Bravo, {name}! Esa palabra ya es tuya",
    "¡Fantástico! Cada día leés mejor",
    "¡Genial! Eres un gran lector",
    "¡Así se hace! Cada día aprendes más",
    "¡Maravilloso, {name}! Tu esfuerzo vale mucho",
    "¡Perfecto! Sigue así, campeón",
    "¡Qué bien lo hiciste! Me encanta cómo aprendes",
    "¡Eres una estrella, {name}! Brillas cada vez más",
    "¡Wow! Esa fue rapidísima",
    "¡Súper, {name}! Ya casi eres un maestro de la lectura",
    "¡Increíble! Cada palabra te hace más fuerte",
    "¡Lo ves? ¡Puedes con todo!",
  ],
  farewells: [
    "¡Fue una gran clase, {name}! Nos vemos mañana",
    "¡Aprendiste mucho hoy! ¡Nos vemos pronto!",
    "¡Hasta la próxima, {name}! Recuerda: tú eres un gran lector",
    "¡Qué clase tan bonita! Descansa y mañana seguimos",
    "¡Adiós, {name}! Hoy brillaste mucho",
    "¡Nos vemos pronto! Hoy fue un gran día de lectura",
    "¡Hasta mañana! Recuerda que la Seño Sofía siempre cree en ti",
    "¡Chao, {name}! Hoy aprendimos palabras hermosas juntos",
  ],
  onMistake: [
    "¡Casi! Intentemos otra vez, tú puedes",
    "No te preocupes, aprender es intentar muchas veces",
    "Esa es difícil, pero juntos la vamos a aprender",
    "¡Buen intento, {name}! Vamos a verla una vez más",
    "No pasa nada, cada intento te acerca más",
    "¡Ánimo! Los mejores lectores también practican mucho",
    "Esa palabra es traviesa, pero tú eres más listo",
    "¡Tranquilo, {name}! Yo también tuve que practicar mucho",
    "¡Sigue intentando! Cada vez estás más cerca",
    "No hay prisa, vamos a tu ritmo",
  ],
};
